### PR TITLE
Topics for 30.06.2018

### PR DESCRIPTION
**Pull request by IngvarX**
Feel free to suggest your topic below

### CODE REVIEW

**Comment by hugbubby** [comment]
The online-after-many-minutes bug.

**Comment by hugbubby** [comment]
Rust-toxcore.

**Comment by hugbubby** [comment]
Dev recruitment.

**Comment by hugbubby** [comment]
Extending meetings to once every 2-4 weeks so they don't get to be a waste of time. Hard to have a meeting about the 3-4 pull requests that get in every week or so.

**Comment by tox-user** [comment]
@hugbubby
>The online-after-many-minutes bug.

Could you be more specific? What bug are you talking about? Is there an issue for it somewhere?

**Comment by IngvarX** [comment]
@hugbubby Did you mean https://github.com/TokTok/c-toxcore/issues/904 ?

**Comment by tox-user** [comment]
https://github.com/TokTok/c-toxcore/issues/904 is a LAN discovery bug in toxcore or in qTox.

**Pull request merged**
