### PR TITLE
Add meeting duration and log info

### PR DESCRIPTION
**Pull request by sudden6**

### CODE REVIEW

**Comment by tox-user** [comment]
I was thinking that it should be around 1h, so if a meeting is 1h and 15 minutes long that would still be fine. What do you think?

**Comment by sudden6** [comment]
It will be longer anyway, so I hope if I word it more strict it won't be too much longer ;)

**Comment by tox-user** [comment]
Is saying UTC+00:00 necessary? It's the same as just saying UTC or GMT.

**Comment by sudden6** [comment]
AFAIK this is a standard way to represent this timezone

**Pull request merged**
