### PR TITLE
Add topics for 23.06.2018

### PR DESCRIPTION
**Pull request by tox-user**
Please add suggestions below.

### CODE REVIEW

**Comment by SkyzohKey** [comment]
Persistent groupchats

**Comment by SkyzohKey** [comment]
WebRTC support

**Comment by SkyzohKey** [comment]
ToxCon2018

**Comment by IngvarX** [comment]
I think we should add:
1) Tox development team
2) Tox development goals
3) New group chats
4) Bots development

**Comment by alnesbit** [comment]
From @alnesbit a.k.a. **ullbeking** in Freenode:

- project structure and leadership (who is who, what responsibilities do they have, what expectations do we have of them?)
- project goals and development goals
- development workflows

**Comment by ullbeking** [comment]
Topics of interest to @ullbeking:
-   project structure and leadership (who is who, what responsibilities do they have, what expectations do we have of them?)
-   project goals and development goals
-   development workflows
-   using Tox on proprietary devices versus libre devices; for example, I only use Tox (and GnuPG, etc) on libre devices because I don't trust proprietary devices
-   ToxCon 2018

**Comment by kurnevsky** [comment]
Capabilities:
- what features will it include?
- will it be backward compatible?
- how exactly it's going to be implemented?

**Comment by tox-user** [comment]
All of them are added. Is that enough topics for the first meeting? I wouldn't want it to take hours to discuss all of them and we can talk about all of remaining things on the meeting after this one.

**Comment by ullbeking** [comment]
@tox-user 
> All of them are added. Is that enough topics for the first meeting?

It's more than enough topics for a first meeting.

> I wouldn't want it to take hours to discuss all of them and we can talk about all of remaining things on the meeting after this one.

Any successful meeting needs an agenda, a **strict time limit**, somebody to moderate, somebody to take notes and write up minutes afterwards.  Before the end of the meeting we will need to generally agree on **actions** that result from the meeting and note what topics will be brought forward to next meeting.

**Pull request merged**
